update packages
ColumbiaRoad/net-impact-bot pull request #35
Opened 2024-01-25 16:16 UTC by mgdemel

Including one breaking change: install axios@1.6.6
Ran dev locally, and nothing broke.

2024-01-26 10:53 UTC, joonasnuutinen reviewed
Seems to work!

2024-01-26 10:53 UTC, joonasnuutinen commented on package.json
The `"engines"` property sets `"node": "16.x"`. The LTS "recommended for most users" is currently 20. When running `npm i`, I get the following warning:

```bash
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'impact-helper-api@2.2.0',
npm WARN EBADENGINE   required: { node: '16.x' },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }
```

Should we either update the engine to include 20 or omit it altogether?

2024-01-29 06:25 UTC, mgdemel commented on package.json
I'll take a look at the pros and cons

2024-01-29 06:29 UTC, mgdemel commented on package.json
I can see that this was set to 16.x in a commit that configured the Heroku deployment. We should check if updating would impact that somehow.

2024-01-29 07:29 UTC, joonasnuutinen commented on package.json
Ah, good point! Then let's keep it and just update it to `20.x`.

2024-02-02 08:52 UTC, joonasnuutinen requested changes
Great job! Just one minor thing and this is ready.

2024-02-02 08:52 UTC, joonasnuutinen commented on package-lock.json
Run `npm i` once again to update the `package-lock` after the Node version change.

2024-02-02 09:15 UTC, mgdemel commented on package-lock.json
Done! :)

2024-02-02 12:13 UTC, joonasnuutinen approved these changes
🚀

2024-02-02 12:16 UTC, merged